import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1>Congratulations! You've completed the <a href="https://resources.github.com/learn/pathways/automation/essentials/automated-application-deployment-with-github-actions-and-pages/">Essentials of automated application deployment with GitHub Actions and GitHub Pages module! 🥳</a></h1>


      </main>
    </>
  )
}
